---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/germangu/public_html/ && /bin/rsync -av --delete --exclude=.git --exclude=.github --exclude=logs --exclude=public/uploads --exclude=.cpanel.yml --exclude=*.sql ./ $DEPLOYPATH
